baseurl = "https://www.datascienceexplorer.com" # Hostname (and path) to the root.
title = "Data Science Explorer" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The siteâ€™s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Will Bidstrup" # Author's name.
    info = "Exploration journal" # Author's job title or info.
    description = "Will Bidstrup's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/viking.png" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Enter a text here." # Add footer content

   # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

   

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/willbidstrup/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/willbidstrup/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/willbidstrup/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/post/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
[[menu.main]]
    name = "Tags"
    weight = 2
    url = "/tags/"
